version: "3.8"

services:
  server:
    build:
        context: ./backend
        dockerfile: Dockerfile
    volumes:
        - ./backend/:/backend/
    command: [
        "uvicorn", 
        "app.api.server:app", 
        "--reload", 
        "--workers", "1", 
        "--host", "0.0.0.0", 
        "--port", "8000"
        ]
    env_file:
        - ./backend/.env
    ports:
        - 8000:8000

#   api_db:
#     image: postgres:14.0
#     container_name: api_db
#     environment:
#         POSTGRES_USER: api_db
#         POSTGRES_DB: api_db
#         POSTGRES_PASSWORD: api_db
#     volumes:
#         - db_data_api:/var/lib/postgresql/data/
#     networks:
#         - backend

# networks:
#     backend:

# volumes:
#     db_data_api:
