version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
        - 80:80
    depends_on:
        - api_db
    volumes:
        - .:/code

  api_db:
    image: postgres:14.0
    container_name: api_db
    environment:
        POSTGRES_USER: api_db
        POSTGRES_DB: api_db
        POSTGRES_PASSWORD: api_db
    volumes:
        - db_data_api:/var/lib/postgresql/data/
    networks:
        - backend

networks:
    backend:

volumes:
    db_data_api:
